version: '3'
services:
  mytelegrambot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/wireguard:/etc/wireguard
    network_mode: host
    ports:
      - 51830:51830/udp
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: always
